import { apiSlice } from "./apiSlice";

// inject product-related endpoints into the shared api slice
// all hooks (useGetProductsQuery, etc.) are auto-generated by rtk query
export const productsApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // fetch all products — usage: const { data, isLoading } = useGetProductsQuery()
    getProducts: builder.query({
      query: () => "/products",
      // invalidate this cache when a product is added, updated, or deleted
      providesTags: ["Products"],
    }),

    // fetch a single product by id — usage: const { data } = useGetProductByIdQuery(id)
    getProductById: builder.query({
      query: (id) => `/products/${id}`,
      providesTags: (result, error, id) => [{ type: "Products", id }],
    }),

    // create a product — usage: const [createProduct] = useCreateProductMutation()
    createProduct: builder.mutation({
      query: (newProduct) => ({
        url: "/products",
        method: "POST",
        body: newProduct,
      }),
      // refetch the products list after creating
      invalidatesTags: ["Products"],
    }),
  }),

  // do not override existing endpoints if this file is loaded twice
  overrideExisting: false,
});

// export the auto-generated hooks for use in components
export const {
  useGetProductsQuery,
  useGetProductByIdQuery,
  useCreateProductMutation,
} = productsApi;
