import { apiSlice } from "./apiSlice";

export interface Product {
  id: number;
  title: string;
  price: number;
  description: string;
  images: string[];
  category: {
    id: number;
    name: string;
    image: string;
  };
}

// inject product-related endpoints into the shared api slice
// all hooks (useGetProductsQuery, etc.) are auto-generated by rtk query
export const productsApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // fetch all products — usage: const { data, isLoading } = useGetProductsQuery()
    getProducts: builder.query<Product[], void>({
      query: () => "/products",
      // invalidate this cache when a product is added, updated, or deleted
      providesTags: ["Products"],
    }),

    // fetch a single product by id — usage: const { data } = useGetProductByIdQuery(id)
    getProductById: builder.query<Product, number>({
      query: (id) => `/products/${id}`,
      providesTags: (result, error, id) => [{ type: "Products", id }],
    }),
  }),

  // do not override existing endpoints if this file is loaded twice
  overrideExisting: false,
});

// export the auto-generated hooks for use in components
export const {
  useGetProductsQuery,
  useGetProductByIdQuery,
} = productsApi;
